title: IVAN ANTEŠIĆ
logo: /assets/img/logo.png
description: ivan.v.antesic@gmail.com
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

github:
  owner_url: https://github.com/ia6382
  
itchio:
  url: https://ivan-antesic.itch.io/
  
projects:
  url: ./projects.html
  
email:
  url: mailto:ivan.v.antesic@gmail.com
